### ISSUE TITLE
How about a BrainFuck interpreter?

### ISSUE THREAD

**Issue by christianbender** [AustinTice/JobInterviewAlgorithms#36]
How about a BrainFuck interpreter? Its a simple programming language and we can simply build interpreter and compiler for it. level of difficulty : 
* Level 1 : for simple loops.  
* Level 2:  for nested loops. 

**Algorithm**
Name:  Simple BrainFuck-Interpreter

Short Description: A simply interpreter for the programming language ```BrainFuck```. 

Programming language: Any

Reference Page: [BrainFuck](https://en.wikipedia.org/wiki/Brainfuck)

**Comment by AustinTice** [comment]
In my opinion this is not in the scope of an interview question that we're looking to cater to. Although, it would be interesting on the side, I don't think it's best for the repo.
