### ISSUE TITLE
Help with Hierarchy

### ISSUE THREAD

**Issue by AustinTice** [AustinTice/JobInterviewAlgorithms#5]
I'm having some issues setting up the hierarchy of the directories. Can someone take this on and send in a PR?

I would like it to go
* Algorithms
     * [Algorithm Name]
          * [Algorithm Solutions]

**Comment by JGFM4** [comment]
If you want,  I can take a look at this later tonight.

**Comment by AustinTice** [comment]
@JGFM4 that would be sublime. I'll work on writing some new algo's that people can branch off of once I get out of class today.

**Comment by JGFM4** [comment]
Awesome. I DMed you on Twitter. If you want to chat about solutions/hierarchy formats, we can chat there

**Comment by AustinTice** [comment]
We will be changing pace on this. I think the best idea is to have [Name of Algorithm] > [Languages] > [Solution]

I will be working on this hierarchy in the following days. Forgive my lack of knowledge in this arena, but @JGFM4 if you want to help on this that'd be excellent.

**Comment by JGFM4** [comment]
This seems like a good structure.   I can hopefully restructure the repo tomorrow night.

**Comment by AustinTice** [comment]
I'm working currently, and will be tomorrow as well, on this restructure. I will stay in contact with you via twitter to monitor the hierarchy process, but I am going to close this issue for now as the plan has been decided upon.
