### ISSUE TITLE
Contribution Guidelines / Style Guide

### ISSUE THREAD

**Issue by AustinTice** [AustinTice/JobInterviewAlgorithms#9]
I like the new implementation of the README in each repo(#8) , along with the templates directory that houses how each should be formatted, but I think we need to create contributions guidelines page. As far as what is expected when a PR is opened. Things like being sure the Algo Directory is TitleCase, It includes the directory path of the language name, as well as some other nuances we could add.

Let me know about your thoughts on this one @JGFM4

**Comment by AustinTice** [comment]
To add on this, would you say that we should delete the documentation that is already in some of the files, and just leave the pure code since the readme will have that data?

**Comment by JGFM4** [comment]
I think a contribution page would be appropriate for sure.

As for the second part, I think solutions should be only code (comments being to explain a part of the code) and the problem definition/documentation should be held in the algorithms' README. It's irrelevant that a friend or you were asked X in an interview. Comments relevant to the solution should be added in the notes section of the README for that Algorithm

**Comment by JGFM4** [comment]
@AustinTice I was thinking of starting the Wiki for the guidelines within the upcoming weeks to solve this issue.

**Comment by AustinTice** [comment]
That would be awesome. Don't feel like you have to do it all alone, feel free to reach out for any troubles or questions. I think we should tag team this to ensure it's written correctly the first time around. Great initiative!

**Comment by AustinTice** [comment]
Done by @JGFM4 good work.
